# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.

draw_bold_text_with_bright_colors = true

# Window decorations
#
# Available values:
# - `full`: Window with title bar and title bar buttons
# - `none`: Window without title bar, rounded corners, or drop shadow
# - `transparent`: Window with title bar with transparent background and title
#   bar buttons
# - `buttonless`: Window with title bar with transparent background and no
#   title bar buttons
# Window decorations
#
# Values for `decorations`:
#     - full: Borders and title bar
#     - none: Neither borders nor title bar
#     - buttonless: Title bar, transparent background and title bar buttons
#     - transparent: Title bar, transparent background, but no title bar buttons
[window]
opacity = 0.4
blur = true
decorations = "None"

# Window dimensions (changes require restart)
#
# Specified in number of columns/lines, not pixels.
# If both are `0`, this setting is ignored.
[window.demensions]
column = 80
lines = 24

# Window padding (changes require restart)
#
# Blank space added around the window in pixels. This padding is not scaled
# by DPI and the specified value is always added at both opposing sides.
[window.padding]
x = 4
y = 4

# Font configuration (changes require restart)
[font]
size = 13.0

[font.normal]
family = "HackGen Console NF"
[font.bold]
family = "HackGen Console NF"
[font.italic]
family = "HackGen Console NF"

[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 10000
# Number of lines the viewport will move for every line scrolled when
# scrollback is enabled (history > 0).
multiplier = 3

[terminal.shell]
program = "/usr/local/bin/bash"
args = ["-l", "-c", "/usr/local/bin/tmux a -t 0 || /usr/local/bin/tmux -u"]

[colors.primary]
background = "#282828"
foreground = "#eeeeee"

[colors.normal]
black = "#282828"
red = "#f43753"
green = "#c9d05c"
yellow = "#ffc24b"
blue = "#b3deef"
magenta = "#d3b987"
cyan = "#73cef4"
white = "#eeeeee"

[colors.bright]
black = "#4c4c4c"
red = "#f43753"
green = "#c9d05c"
yellow = "#ffc24b"
blue = "#b3deef"
magenta = "#d3b987"
cyan = "#73cef4"
white = "#feffff"

[env]
TERM = "screen-256color"
