[window]
opacity = 0.4
blur = true
decorations = "None"

[window.padding]
x = 4
y = 4

[font]
size = 13.0

[font.normal]
family = "HackGen Console NF"
[font.bold]
family = "HackGen Console NF"
[font.italic]
family = "HackGen Console NF"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/usr/local/bin/bash"
args = ["-l", "-c", "/usr/local/bin/tmux a -t 0 || /usr/local/bin/tmux -u"]

[colors.primary]
background = "#282828"
foreground = "#eeeeee"

[colors.normal]
black = "#282828"
red = "#f43753"
green = "#c9d05c"
yellow = "#ffc24b"
blue = "#b3deef"
magenta = "#d3b987"
cyan = "#73cef4"
white = "#eeeeee"

[colors.bright]
black = "#4c4c4c"
red = "#f43753"
green = "#c9d05c"
yellow = "#ffc24b"
blue = "#b3deef"
magenta = "#d3b987"
cyan = "#73cef4"
white = "#feffff"

[env]
TERM = "screen-256color"
